"""Initial migration

Revision ID: a0f07a6c0639
Revises: 
Create Date: 2026-09-25 00:46:08.039342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0f07a6c0639'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lots_id'), 'lots', ['id'], unique=False)
    op.create_index(op.f('ix_lots_lot_id'), 'lots', ['lot_id'], unique=True)
    op.create_table('screening_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('total_components', sa.Integer(), nullable=True),
    sa.Column('pass_count', sa.Integer(), nullable=True),
    sa.Column('monitor_count', sa.Integer(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('reject_count', sa.Integer(), nullable=True),
    sa.Column('repeat_measurement_count', sa.Integer(), nullable=True),
    sa.Column('data_unavailable_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_runs_id'), 'screening_runs', ['id'], unique=False)
    op.create_index(op.f('ix_screening_runs_run_id'), 'screening_runs', ['run_id'], unique=True)
    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.String(), nullable=False),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('lot_id', sa.String(), nullable=True),
    sa.Column('station_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.lot_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_components_component_id'), 'components', ['component_id'], unique=True)
    op.create_index(op.f('ix_components_id'), 'components', ['id'], unique=False)
    op.create_index(op.f('ix_components_lot_id'), 'components', ['lot_id'], unique=False)
    op.create_index(op.f('ix_components_station_id'), 'components', ['station_id'], unique=False)
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('hour', sa.String(), nullable=True),
    sa.Column('temperature', sa.String(), nullable=True),
    sa.Column('voltage', sa.String(), nullable=True),
    sa.Column('iddq_ua', sa.Float(), nullable=True),
    sa.Column('leakage_na', sa.Float(), nullable=True),
    sa.Column('prop_delay_ns', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.component_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurements_component_id'), 'measurements', ['component_id'], unique=False)
    op.create_index(op.f('ix_measurements_hour'), 'measurements', ['hour'], unique=False)
    op.create_index(op.f('ix_measurements_id'), 'measurements', ['id'], unique=False)
    op.create_index(op.f('ix_measurements_timestamp'), 'measurements', ['timestamp'], unique=False)
    op.create_table('screening_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.String(), nullable=True),
    sa.Column('ldi', sa.Float(), nullable=True),
    sa.Column('a_score', sa.Float(), nullable=True),
    sa.Column('s_score', sa.Float(), nullable=True),
    sa.Column('prediction_risk', sa.Float(), nullable=True),
    sa.Column('uncertainty_risk', sa.Float(), nullable=True),
    sa.Column('predicted_168h', sa.JSON(), nullable=True),
    sa.Column('prediction_lower', sa.Float(), nullable=True),
    sa.Column('prediction_upper', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('integrity_flag', sa.Boolean(), nullable=True),
    sa.Column('basis_mode', sa.String(), nullable=True),
    sa.Column('b_model', sa.String(), nullable=True),
    sa.Column('calibration', sa.Boolean(), nullable=True),
    sa.Column('basis', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('test_integrity', sa.JSON(), nullable=True),
    sa.Column('history', sa.JSON(), nullable=True),
    sa.Column('b_models', sa.JSON(), nullable=True),
    sa.Column('shap', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.component_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_results_component_id'), 'screening_results', ['component_id'], unique=False)
    op.create_index(op.f('ix_screening_results_created_at'), 'screening_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_screening_results_decision'), 'screening_results', ['decision'], unique=False)
    op.create_index(op.f('ix_screening_results_id'), 'screening_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screening_results_id'), table_name='screening_results')
    op.drop_index(op.f('ix_screening_results_decision'), table_name='screening_results')
    op.drop_index(op.f('ix_screening_results_created_at'), table_name='screening_results')
    op.drop_index(op.f('ix_screening_results_component_id'), table_name='screening_results')
    op.drop_table('screening_results')
    op.drop_index(op.f('ix_measurements_timestamp'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_id'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_hour'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_component_id'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_index(op.f('ix_components_station_id'), table_name='components')
    op.drop_index(op.f('ix_components_lot_id'), table_name='components')
    op.drop_index(op.f('ix_components_id'), table_name='components')
    op.drop_index(op.f('ix_components_component_id'), table_name='components')
    op.drop_table('components')
    op.drop_index(op.f('ix_screening_runs_run_id'), table_name='screening_runs')
    op.drop_index(op.f('ix_screening_runs_id'), table_name='screening_runs')
    op.drop_table('screening_runs')
    op.drop_index(op.f('ix_lots_lot_id'), table_name='lots')
    op.drop_index(op.f('ix_lots_id'), table_name='lots')
    op.drop_table('lots')
    # ### end Alembic commands ###
