"""Phase 1 schema foundation

Revision ID: d02aff198329
Revises: a0f07a6c0639
Create Date: 2026-09-27 18:51:22.267583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd02aff198329'
down_revision: Union[str, Sequence[str], None] = 'a0f07a6c0639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('artifact_name', sa.String(), nullable=True),
    sa.Column('artifact_path', sa.String(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('sklearn_version', sa.String(), nullable=True),
    sa.Column('numpy_version', sa.String(), nullable=True),
    sa.Column('loaded_status', sa.String(), nullable=True),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_id'), 'model_versions', ['id'], unique=False)
    op.create_table('anomaly_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('component_id', sa.String(), nullable=False),
    sa.Column('pat_score', sa.Float(), nullable=True),
    sa.Column('pat_evidence', sa.JSON(), nullable=True),
    sa.Column('peer_score', sa.Float(), nullable=True),
    sa.Column('peer_evidence', sa.JSON(), nullable=True),
    sa.Column('temporal_score', sa.Float(), nullable=True),
    sa.Column('temporal_evidence', sa.JSON(), nullable=True),
    sa.Column('isolation_forest_score', sa.Float(), nullable=True),
    sa.Column('isolation_forest_evidence', sa.JSON(), nullable=True),
    sa.Column('a_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.component_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['screening_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_evidence_component_id'), 'anomaly_evidence', ['component_id'], unique=False)
    op.create_index(op.f('ix_anomaly_evidence_id'), 'anomaly_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_anomaly_evidence_run_id'), 'anomaly_evidence', ['run_id'], unique=False)
    op.create_table('anomaly_origins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('component_id', sa.String(), nullable=True),
    sa.Column('lot_id', sa.String(), nullable=True),
    sa.Column('station_id', sa.String(), nullable=True),
    sa.Column('device_status', sa.String(), nullable=True),
    sa.Column('lot_status', sa.String(), nullable=True),
    sa.Column('station_status', sa.String(), nullable=True),
    sa.Column('device_score', sa.Float(), nullable=True),
    sa.Column('lot_score', sa.Float(), nullable=True),
    sa.Column('station_score', sa.Float(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.component_id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.lot_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['screening_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_origins_component_id'), 'anomaly_origins', ['component_id'], unique=False)
    op.create_index(op.f('ix_anomaly_origins_id'), 'anomaly_origins', ['id'], unique=False)
    op.create_index(op.f('ix_anomaly_origins_lot_id'), 'anomaly_origins', ['lot_id'], unique=False)
    op.create_index(op.f('ix_anomaly_origins_run_id'), 'anomaly_origins', ['run_id'], unique=False)
    op.create_index(op.f('ix_anomaly_origins_station_id'), 'anomaly_origins', ['station_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('component_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.component_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['screening_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_component_id'), 'audit_events', ['component_id'], unique=False)
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_index(op.f('ix_audit_events_run_id'), 'audit_events', ['run_id'], unique=False)
    op.create_table('lot_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('lot_id', sa.String(), nullable=False),
    sa.Column('lot_shift_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('affected_component_count', sa.Integer(), nullable=True),
    sa.Column('total_component_count', sa.Integer(), nullable=True),
    sa.Column('parameter_evidence', sa.JSON(), nullable=True),
    sa.Column('distribution_evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.lot_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['screening_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lot_analysis_id'), 'lot_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_lot_analysis_lot_id'), 'lot_analysis', ['lot_id'], unique=False)
    op.create_index(op.f('ix_lot_analysis_run_id'), 'lot_analysis', ['run_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('component_id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('prediction_stage', sa.String(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('predicted_168h', sa.JSON(), nullable=True),
    sa.Column('input_checkpoint', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.component_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['screening_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_component_id'), 'predictions', ['component_id'], unique=False)
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_run_id'), 'predictions', ['run_id'], unique=False)
    op.create_table('risk_fusion_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('component_id', sa.String(), nullable=False),
    sa.Column('a_score', sa.Float(), nullable=True),
    sa.Column('s_score', sa.Float(), nullable=True),
    sa.Column('prediction_risk', sa.Float(), nullable=True),
    sa.Column('uncertainty_risk', sa.Float(), nullable=True),
    sa.Column('ldi', sa.Float(), nullable=True),
    sa.Column('fusion_score', sa.Float(), nullable=True),
    sa.Column('final_decision', sa.String(), nullable=True),
    sa.Column('decision_basis', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.component_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['screening_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_fusion_results_component_id'), 'risk_fusion_results', ['component_id'], unique=False)
    op.create_index(op.f('ix_risk_fusion_results_id'), 'risk_fusion_results', ['id'], unique=False)
    op.create_index(op.f('ix_risk_fusion_results_run_id'), 'risk_fusion_results', ['run_id'], unique=False)
    op.create_table('safety_envelopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('component_id', sa.String(), nullable=False),
    sa.Column('parameter', sa.String(), nullable=True),
    sa.Column('lower', sa.Float(), nullable=True),
    sa.Column('upper', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.component_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['screening_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_envelopes_component_id'), 'safety_envelopes', ['component_id'], unique=False)
    op.create_index(op.f('ix_safety_envelopes_id'), 'safety_envelopes', ['id'], unique=False)
    op.create_index(op.f('ix_safety_envelopes_run_id'), 'safety_envelopes', ['run_id'], unique=False)
    op.create_table('station_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('lot_id', sa.String(), nullable=True),
    sa.Column('station_id', sa.String(), nullable=False),
    sa.Column('station_shift_score', sa.Float(), nullable=True),
    sa.Column('integrity_status', sa.String(), nullable=True),
    sa.Column('within_station_evidence', sa.JSON(), nullable=True),
    sa.Column('cross_station_evidence', sa.JSON(), nullable=True),
    sa.Column('parameter_evidence', sa.JSON(), nullable=True),
    sa.Column('affected_component_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.lot_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['screening_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_analysis_id'), 'station_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_station_analysis_lot_id'), 'station_analysis', ['lot_id'], unique=False)
    op.create_index(op.f('ix_station_analysis_run_id'), 'station_analysis', ['run_id'], unique=False)
    op.create_index(op.f('ix_station_analysis_station_id'), 'station_analysis', ['station_id'], unique=False)
    op.create_table('prediction_intervals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(), nullable=True),
    sa.Column('lower', sa.Float(), nullable=True),
    sa.Column('upper', sa.Float(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('calibrated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_intervals_id'), 'prediction_intervals', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_intervals_prediction_id'), 'prediction_intervals', ['prediction_id'], unique=False)
    op.alter_column('components', 'lot_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('measurements', sa.Column('run_id', sa.String(), nullable=True))
    op.add_column('measurements', sa.Column('checkpoint_hour', sa.Integer(), nullable=False))
    op.add_column('measurements', sa.Column('source_row_number', sa.Integer(), nullable=True))
    op.alter_column('measurements', 'component_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_measurements_hour'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_timestamp'), table_name='measurements')
    op.create_index(op.f('ix_measurements_checkpoint_hour'), 'measurements', ['checkpoint_hour'], unique=False)
    op.create_index(op.f('ix_measurements_run_id'), 'measurements', ['run_id'], unique=False)
    op.create_unique_constraint('uq_run_comp_chkpt', 'measurements', ['run_id', 'component_id', 'checkpoint_hour'])
    op.create_foreign_key(None, 'measurements', 'screening_runs', ['run_id'], ['run_id'])
    op.drop_column('measurements', 'hour')
    op.add_column('screening_results', sa.Column('run_id', sa.String(), nullable=True))
    op.add_column('screening_results', sa.Column('integrity_status', sa.String(), nullable=True))
    op.add_column('screening_results', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('screening_results', 'component_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_screening_results_run_id'), 'screening_results', ['run_id'], unique=False)
    op.create_unique_constraint('uq_run_comp_result', 'screening_results', ['run_id', 'component_id'])
    op.create_foreign_key(None, 'screening_results', 'screening_runs', ['run_id'], ['run_id'])
    op.drop_column('screening_results', 'b_models')
    op.drop_column('screening_results', 'integrity_flag')
    op.drop_column('screening_results', 'predicted_168h')
    op.drop_column('screening_results', 'prediction_upper')
    op.drop_column('screening_results', 'basis')
    op.drop_column('screening_results', 'prediction_lower')
    op.drop_column('screening_results', 'b_model')
    op.drop_column('screening_results', 'history')
    op.drop_column('screening_results', 'test_integrity')
    op.drop_column('screening_results', 'explanation')
    op.drop_column('screening_results', 'basis_mode')
    op.drop_column('screening_results', 'shap')
    op.drop_column('screening_results', 'calibration')
    op.add_column('screening_runs', sa.Column('lot_id', sa.String(), nullable=True))
    op.add_column('screening_runs', sa.Column('source_filename', sa.String(), nullable=True))
    op.add_column('screening_runs', sa.Column('source_file_hash', sa.String(), nullable=True))
    op.add_column('screening_runs', sa.Column('status', sa.String(), nullable=True))
    op.add_column('screening_runs', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('screening_runs', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('screening_runs', sa.Column('total_rows', sa.Integer(), nullable=True))
    op.add_column('screening_runs', sa.Column('valid_rows', sa.Integer(), nullable=True))
    op.add_column('screening_runs', sa.Column('invalid_rows', sa.Integer(), nullable=True))
    op.add_column('screening_runs', sa.Column('component_count', sa.Integer(), nullable=True))
    op.add_column('screening_runs', sa.Column('warning_count', sa.Integer(), nullable=True))
    op.add_column('screening_runs', sa.Column('error_count', sa.Integer(), nullable=True))
    op.add_column('screening_runs', sa.Column('model_version', sa.String(), nullable=True))
    op.alter_column('screening_runs', 'run_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_screening_runs_lot_id'), 'screening_runs', ['lot_id'], unique=False)
    op.create_foreign_key(None, 'screening_runs', 'lots', ['lot_id'], ['lot_id'])
    op.drop_column('screening_runs', 'review_count')
    op.drop_column('screening_runs', 'repeat_measurement_count')
    op.drop_column('screening_runs', 'data_unavailable_count')
    op.drop_column('screening_runs', 'monitor_count')
    op.drop_column('screening_runs', 'total_components')
    op.drop_column('screening_runs', 'reject_count')
    op.drop_column('screening_runs', 'pass_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screening_runs', sa.Column('pass_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('screening_runs', sa.Column('reject_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('screening_runs', sa.Column('total_components', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('screening_runs', sa.Column('monitor_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('screening_runs', sa.Column('data_unavailable_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('screening_runs', sa.Column('repeat_measurement_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('screening_runs', sa.Column('review_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'screening_runs', type_='foreignkey')
    op.drop_index(op.f('ix_screening_runs_lot_id'), table_name='screening_runs')
    op.alter_column('screening_runs', 'run_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('screening_runs', 'model_version')
    op.drop_column('screening_runs', 'error_count')
    op.drop_column('screening_runs', 'warning_count')
    op.drop_column('screening_runs', 'component_count')
    op.drop_column('screening_runs', 'invalid_rows')
    op.drop_column('screening_runs', 'valid_rows')
    op.drop_column('screening_runs', 'total_rows')
    op.drop_column('screening_runs', 'completed_at')
    op.drop_column('screening_runs', 'started_at')
    op.drop_column('screening_runs', 'status')
    op.drop_column('screening_runs', 'source_file_hash')
    op.drop_column('screening_runs', 'source_filename')
    op.drop_column('screening_runs', 'lot_id')
    op.add_column('screening_results', sa.Column('calibration', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('screening_results', sa.Column('shap', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('screening_results', sa.Column('basis_mode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('screening_results', sa.Column('explanation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('screening_results', sa.Column('test_integrity', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('screening_results', sa.Column('history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('screening_results', sa.Column('b_model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('screening_results', sa.Column('prediction_lower', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('screening_results', sa.Column('basis', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('screening_results', sa.Column('prediction_upper', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('screening_results', sa.Column('predicted_168h', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('screening_results', sa.Column('integrity_flag', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('screening_results', sa.Column('b_models', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'screening_results', type_='foreignkey')
    op.drop_constraint('uq_run_comp_result', 'screening_results', type_='unique')
    op.drop_index(op.f('ix_screening_results_run_id'), table_name='screening_results')
    op.alter_column('screening_results', 'component_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('screening_results', 'updated_at')
    op.drop_column('screening_results', 'integrity_status')
    op.drop_column('screening_results', 'run_id')
    op.add_column('measurements', sa.Column('hour', sa.VARCHAR(), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'measurements', type_='foreignkey')
    op.drop_constraint('uq_run_comp_chkpt', 'measurements', type_='unique')
    op.drop_index(op.f('ix_measurements_run_id'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_checkpoint_hour'), table_name='measurements')
    op.create_index(op.f('ix_measurements_timestamp'), 'measurements', ['timestamp'], unique=False)
    op.create_index(op.f('ix_measurements_hour'), 'measurements', ['hour'], unique=False)
    op.alter_column('measurements', 'component_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('measurements', 'source_row_number')
    op.drop_column('measurements', 'checkpoint_hour')
    op.drop_column('measurements', 'run_id')
    op.alter_column('components', 'lot_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_prediction_intervals_prediction_id'), table_name='prediction_intervals')
    op.drop_index(op.f('ix_prediction_intervals_id'), table_name='prediction_intervals')
    op.drop_table('prediction_intervals')
    op.drop_index(op.f('ix_station_analysis_station_id'), table_name='station_analysis')
    op.drop_index(op.f('ix_station_analysis_run_id'), table_name='station_analysis')
    op.drop_index(op.f('ix_station_analysis_lot_id'), table_name='station_analysis')
    op.drop_index(op.f('ix_station_analysis_id'), table_name='station_analysis')
    op.drop_table('station_analysis')
    op.drop_index(op.f('ix_safety_envelopes_run_id'), table_name='safety_envelopes')
    op.drop_index(op.f('ix_safety_envelopes_id'), table_name='safety_envelopes')
    op.drop_index(op.f('ix_safety_envelopes_component_id'), table_name='safety_envelopes')
    op.drop_table('safety_envelopes')
    op.drop_index(op.f('ix_risk_fusion_results_run_id'), table_name='risk_fusion_results')
    op.drop_index(op.f('ix_risk_fusion_results_id'), table_name='risk_fusion_results')
    op.drop_index(op.f('ix_risk_fusion_results_component_id'), table_name='risk_fusion_results')
    op.drop_table('risk_fusion_results')
    op.drop_index(op.f('ix_predictions_run_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_component_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_lot_analysis_run_id'), table_name='lot_analysis')
    op.drop_index(op.f('ix_lot_analysis_lot_id'), table_name='lot_analysis')
    op.drop_index(op.f('ix_lot_analysis_id'), table_name='lot_analysis')
    op.drop_table('lot_analysis')
    op.drop_index(op.f('ix_audit_events_run_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_component_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_anomaly_origins_station_id'), table_name='anomaly_origins')
    op.drop_index(op.f('ix_anomaly_origins_run_id'), table_name='anomaly_origins')
    op.drop_index(op.f('ix_anomaly_origins_lot_id'), table_name='anomaly_origins')
    op.drop_index(op.f('ix_anomaly_origins_id'), table_name='anomaly_origins')
    op.drop_index(op.f('ix_anomaly_origins_component_id'), table_name='anomaly_origins')
    op.drop_table('anomaly_origins')
    op.drop_index(op.f('ix_anomaly_evidence_run_id'), table_name='anomaly_evidence')
    op.drop_index(op.f('ix_anomaly_evidence_id'), table_name='anomaly_evidence')
    op.drop_index(op.f('ix_anomaly_evidence_component_id'), table_name='anomaly_evidence')
    op.drop_table('anomaly_evidence')
    op.drop_index(op.f('ix_model_versions_id'), table_name='model_versions')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
